-- star schema DDL — types resolved from canonical column_types

CREATE TABLE [Dim Customer] (
  [CustomerKey] BIGINT PRIMARY KEY,
  [GeographyKey] BIGINT,
  [CustomerAlternateKey] NVARCHAR(255),
  [Title] NVARCHAR(255),
  [FirstName] NVARCHAR(255),
  [MiddleName] NVARCHAR(255),
  [LastName] NVARCHAR(255),
  [NameStyle] BIT,
  [BirthDate] DATETIME2,
  [MaritalStatus] NVARCHAR(255),
  [Suffix] NVARCHAR(255),
  [Gender] NVARCHAR(255),
  [EmailAddress] NVARCHAR(255),
  [YearlyIncome] DECIMAL(19,4),
  [TotalChildren] BIGINT,
  [NumberChildrenAtHome] BIGINT,
  [EnglishEducation] NVARCHAR(255),
  [EnglishOccupation] NVARCHAR(255),
  [HouseOwnerFlag] NVARCHAR(255),
  [NumberCarsOwned] BIGINT,
  [AddressLine1] NVARCHAR(255),
  [AddressLine2] NVARCHAR(255),
  [Phone] NVARCHAR(255),
  [DateFirstPurchase] DATETIME2,
  [CommuteDistance] NVARCHAR(255),
  [City] NVARCHAR(255),
  [StateProvinceCode] NVARCHAR(255),
  [StateProvince] NVARCHAR(255),
  [CountryCode] NVARCHAR(255),
  [Country] NVARCHAR(255),
  [PostalCode] NVARCHAR(255),
  [SalesTerritoryKey] BIGINT,
  [IpAddressLocator] NVARCHAR(255)
);

CREATE TABLE [Dim Date] (
  [DateKey] BIGINT PRIMARY KEY,
  [Date] DATETIME2,
  [DayNumberOfWeek] BIGINT,
  [EnglishDayNameOfWeek] NVARCHAR(255),
  [DayNumberOfMonth] BIGINT,
  [DayNumberOfYear] BIGINT,
  [WeekNumberOfYear] BIGINT,
  [EnglishMonthName] NVARCHAR(255),
  [MonthNumberOfYear] BIGINT,
  [CalendarQuarter] BIGINT,
  [CalendarYear] BIGINT,
  [CalendarSemester] BIGINT,
  [FiscalQuarter] BIGINT,
  [FiscalYear] BIGINT,
  [FiscalSemester] BIGINT
);

CREATE TABLE [Dim Product] (
  [ProductKey] BIGINT PRIMARY KEY,
  [ProductAlternateKey] NVARCHAR(255),
  [ProductSubcategoryKey] BIGINT,
  [WeightUnitMeasureCode] NVARCHAR(255),
  [SizeUnitMeasureCode] NVARCHAR(255),
  [EnglishProductName] NVARCHAR(255),
  [StandardCost] DECIMAL(19,4),
  [FinishedGoodsFlag] BIT,
  [Color] NVARCHAR(255),
  [SafetyStockLevel] BIGINT,
  [ReorderPoint] BIGINT,
  [ListPrice] DECIMAL(19,4),
  [Size] NVARCHAR(255),
  [SizeRange] NVARCHAR(255),
  [Weight] FLOAT,
  [DaysToManufacture] BIGINT,
  [ProductLine] NVARCHAR(255),
  [DealerPrice] DECIMAL(19,4),
  [Class] NVARCHAR(255),
  [Style] NVARCHAR(255),
  [ModelName] NVARCHAR(255),
  [EnglishDescription] NVARCHAR(255),
  [StartDate] DATETIME2,
  [EndDate] DATETIME2,
  [Status] NVARCHAR(255),
  [ProductSubCategoryName] NVARCHAR(255),
  [ProductCategoryName] NVARCHAR(255),
  [ProductSubcategoryAlternateKey] BIGINT,
  [EnglishProductSubcategoryName] NVARCHAR(255),
  [ProductCategoryKey] BIGINT,
  [ProductCategoryAlternateKey] BIGINT,
  [EnglishProductCategoryName] NVARCHAR(255)
);

CREATE TABLE [Dim Employee] (
  [EmployeeKey] BIGINT PRIMARY KEY,
  [ParentEmployeeKey] BIGINT,
  [EmployeeNationalIDAlternateKey] NVARCHAR(255),
  [ParentEmployeeNationalIDAlternateKey] NVARCHAR(255),
  [SalesTerritoryKey] BIGINT,
  [FirstName] NVARCHAR(255),
  [LastName] NVARCHAR(255),
  [MiddleName] NVARCHAR(255),
  [NameStyle] BIT,
  [Title] NVARCHAR(255),
  [HireDate] DATETIME2,
  [BirthDate] DATETIME2,
  [LoginID] NVARCHAR(255),
  [EmailAddress] NVARCHAR(255),
  [Phone] NVARCHAR(255),
  [MaritalStatus] NVARCHAR(255),
  [EmergencyContactName] NVARCHAR(255),
  [EmergencyContactPhone] NVARCHAR(255),
  [SalariedFlag] BIT,
  [Gender] NVARCHAR(255),
  [PayFrequency] BIGINT,
  [BaseRate] DECIMAL(19,4),
  [VacationHours] BIGINT,
  [SickLeaveHours] BIGINT,
  [CurrentFlag] BIT,
  [SalesPersonFlag] BIT,
  [DepartmentName] NVARCHAR(255),
  [StartDate] DATETIME2,
  [EndDate] DATETIME2,
  [Status] NVARCHAR(255),
  [FullName] NVARCHAR(255),
  [Path] NVARCHAR(255),
  [Level1] NVARCHAR(255),
  [Level2] NVARCHAR(255),
  [Level3] NVARCHAR(255),
  [Level4] NVARCHAR(255),
  [Level5] NVARCHAR(255)
);

CREATE TABLE [Fact Internet Sales] (
  [CustomerKey] BIGINT REFERENCES [Dim Customer] ([CustomerKey]),
  [ProductKey] BIGINT REFERENCES [Dim Product] ([ProductKey]),
  [DueDateKey] BIGINT REFERENCES [Dim Date] ([DateKey]),
  [ShipDateKey] BIGINT REFERENCES [Dim Date] ([DateKey]),
  [OrderDateKey] BIGINT REFERENCES [Dim Date] ([DateKey]),
  [PromotionKey] BIGINT  -- degenerate,
  [CurrencyKey] BIGINT  -- degenerate,
  [SalesTerritoryKey] BIGINT  -- degenerate,
  [SalesOrderNumber] NVARCHAR(255)  -- degenerate,
  [SalesOrderLineNumber] BIGINT  -- degenerate,
  [RevisionNumber] BIGINT  -- degenerate,
  [OrderQuantity] BIGINT  -- degenerate,
  [UnitPrice] DECIMAL(19,4)  -- degenerate,
  [ExtendedAmount] DECIMAL(19,4)  -- degenerate,
  [UnitPriceDiscountPct] FLOAT  -- degenerate,
  [DiscountAmount] FLOAT  -- degenerate,
  [ProductStandardCost] DECIMAL(19,4)  -- degenerate,
  [TotalProductCost] DECIMAL(19,4)  -- degenerate,
  [SalesAmount] DECIMAL(19,4)  -- degenerate,
  [TaxAmt] DECIMAL(19,4)  -- degenerate,
  [Freight] DECIMAL(19,4)  -- degenerate,
  [CarrierTrackingNumber] NVARCHAR(255)  -- degenerate,
  [CustomerPONumber] NVARCHAR(255)  -- degenerate,
  [OrderDate] DATETIME2  -- degenerate,
  [DueDate] DATETIME2  -- degenerate,
  [ShipDate] DATETIME2  -- degenerate,
  [Margin] DECIMAL(19,4)  -- degenerate,
  [InternetDistinctCountSalesOrder] DECIMAL(19,4)  -- none [calc: unresolved],
  [InternetOrderLinesCount] DECIMAL(19,4)  -- none [calc: unresolved],
  [InternetTotalUnits] DECIMAL(19,4)  -- none [calc: unresolved],
  [InternetTotalDiscountAmount] DECIMAL(19,4)  -- none [calc: unresolved],
  [InternetTotalProductCost] DECIMAL(19,4)  -- none [calc: unresolved],
  [InternetTotalSales] DECIMAL(19,4)  -- none [calc: unresolved],
  [InternetTotalTaxAmt] DECIMAL(19,4)  -- none [calc: unresolved],
  [InternetTotalFreight] DECIMAL(19,4)  -- none [calc: unresolved],
  [InternetTotalMargin] DECIMAL(19,4)  -- none [calc: unresolved],
  [InternetCurrentQuarterSalesPerformance] DECIMAL(19,4)  -- none [calc: unresolved],
  [InternetPreviousQuarterMargin] DECIMAL(19,4)  -- none [calc: unresolved],
  [InternetCurrentQuarterMargin] DECIMAL(19,4)  -- none [calc: unresolved],
  [InternetPreviousQuarterMarginProportionToQTD] DECIMAL(19,4)  -- none [calc: unresolved],
  [InternetPreviousQuarterSales] DECIMAL(19,4)  -- none [calc: unresolved],
  [InternetCurrentQuarterSales] DECIMAL(19,4)  -- none [calc: unresolved],
  [InternetPreviousQuarterSalesProportionToQTD] DECIMAL(19,4)  -- none [calc: unresolved],
  [InternetCurrentQuarterMarginPerformance] DECIMAL(19,4)  -- none [calc: unresolved],
  [YTD InternetTotalSales] DECIMAL(19,4)  -- none [calc: unresolved]
);

CREATE TABLE [Fact Reseller Sales] (
  [EmployeeKey] BIGINT REFERENCES [Dim Employee] ([EmployeeKey]),
  [ProductKey] BIGINT REFERENCES [Dim Product] ([ProductKey]),
  [OrderDateKey] BIGINT REFERENCES [Dim Date] ([DateKey]),
  [DueDateKey] BIGINT REFERENCES [Dim Date] ([DateKey]),
  [ShipDateKey] BIGINT REFERENCES [Dim Date] ([DateKey]),
  [ResellerKey] BIGINT  -- degenerate,
  [PromotionKey] BIGINT  -- degenerate,
  [CurrencyKey] BIGINT  -- degenerate,
  [SalesTerritoryKey] BIGINT  -- degenerate,
  [SalesOrderNumber] NVARCHAR(255)  -- degenerate,
  [SalesOrderLineNumber] BIGINT  -- degenerate,
  [RevisionNumber] BIGINT  -- degenerate,
  [OrderQuantity] BIGINT  -- degenerate,
  [UnitPrice] DECIMAL(19,4)  -- degenerate,
  [ExtendedAmount] DECIMAL(19,4)  -- degenerate,
  [UnitPriceDiscountPct] FLOAT  -- degenerate,
  [DiscountAmount] FLOAT  -- degenerate,
  [ProductStandardCost] DECIMAL(19,4)  -- degenerate,
  [TotalProductCost] DECIMAL(19,4)  -- degenerate,
  [SalesAmount] DECIMAL(19,4)  -- degenerate,
  [TaxAmt] DECIMAL(19,4)  -- degenerate,
  [Freight] DECIMAL(19,4)  -- degenerate,
  [CarrierTrackingNumber] NVARCHAR(255)  -- degenerate,
  [CustomerPONumber] NVARCHAR(255)  -- degenerate,
  [OrderDate] DATETIME2  -- degenerate,
  [DueDate] DATETIME2  -- degenerate,
  [ShipDate] DATETIME2  -- degenerate,
  [ResellerTotalSales] DECIMAL(19,4)  -- none [calc: unresolved]
);

-- columns without type info (generated/unmapped), placeholders used: InternetCurrentQuarterMargin, InternetCurrentQuarterMarginPerformance, InternetCurrentQuarterSales, InternetCurrentQuarterSalesPerformance, InternetDistinctCountSalesOrder, InternetOrderLinesCount, InternetPreviousQuarterMargin, InternetPreviousQuarterMarginProportionToQTD, InternetPreviousQuarterSales, InternetPreviousQuarterSalesProportionToQTD, InternetTotalDiscountAmount, InternetTotalFreight, InternetTotalMargin, InternetTotalProductCost, InternetTotalSales, InternetTotalTaxAmt, InternetTotalUnits, ResellerTotalSales, YTD InternetTotalSales
