-- CubeTriage load SQL — Model_aw1400
-- generated; verify before running (validation.sql)

INSERT INTO Dim Customer (CustomerKey, GeographyKey, CustomerAlternateKey, Title, FirstName, MiddleName, LastName, NameStyle, BirthDate, MaritalStatus, Suffix, Gender, EmailAddress, YearlyIncome, TotalChildren, NumberChildrenAtHome, EnglishEducation, EnglishOccupation, HouseOwnerFlag, NumberCarsOwned, AddressLine1, AddressLine2, Phone, DateFirstPurchase, CommuteDistance, City, StateProvinceCode, StateProvince, CountryCode, Country, PostalCode, SalesTerritoryKey, IpAddressLocator)
SELECT Dim Customer.CustomerKey, Dim Customer.GeographyKey, Dim Customer.CustomerAlternateKey, Dim Customer.Title, Dim Customer.FirstName, Dim Customer.MiddleName, Dim Customer.LastName, Dim Customer.NameStyle, Dim Customer.BirthDate, Dim Customer.MaritalStatus, Dim Customer.Suffix, Dim Customer.Gender, Dim Customer.EmailAddress, Dim Customer.YearlyIncome, Dim Customer.TotalChildren, Dim Customer.NumberChildrenAtHome, Dim Customer.EnglishEducation, Dim Customer.EnglishOccupation, Dim Customer.HouseOwnerFlag, Dim Customer.NumberCarsOwned, Dim Customer.AddressLine1, Dim Customer.AddressLine2, Dim Customer.Phone, Dim Customer.DateFirstPurchase, Dim Customer.CommuteDistance, Dim Geography.City, Dim Geography.StateProvinceCode, Dim Geography.StateProvince, Dim Geography.CountryCode, Dim Geography.Country, Dim Geography.PostalCode, Dim Geography.SalesTerritoryKey, Dim Geography.IpAddressLocator
FROM Dim Customer JOIN Dim Geography ON Dim Customer.GeographyKey = Dim Geography.GeographyKey;

INSERT INTO Dim Date (DateKey, Date, DayNumberOfWeek, EnglishDayNameOfWeek, DayNumberOfMonth, DayNumberOfYear, WeekNumberOfYear, EnglishMonthName, MonthNumberOfYear, CalendarQuarter, CalendarYear, CalendarSemester, FiscalQuarter, FiscalYear, FiscalSemester)
SELECT Dim Date.DateKey, Dim Date.Date, Dim Date.DayNumberOfWeek, Dim Date.EnglishDayNameOfWeek, Dim Date.DayNumberOfMonth, Dim Date.DayNumberOfYear, Dim Date.WeekNumberOfYear, Dim Date.EnglishMonthName, Dim Date.MonthNumberOfYear, Dim Date.CalendarQuarter, Dim Date.CalendarYear, Dim Date.CalendarSemester, Dim Date.FiscalQuarter, Dim Date.FiscalYear, Dim Date.FiscalSemester
FROM Dim Date;

INSERT INTO Dim Product (ProductKey, ProductAlternateKey, ProductSubcategoryKey, WeightUnitMeasureCode, SizeUnitMeasureCode, EnglishProductName, StandardCost, FinishedGoodsFlag, Color, SafetyStockLevel, ReorderPoint, ListPrice, Size, SizeRange, Weight, DaysToManufacture, ProductLine, DealerPrice, Class, Style, ModelName, EnglishDescription, StartDate, EndDate, Status, ProductSubCategoryName, ProductCategoryName, ProductSubcategoryAlternateKey, EnglishProductSubcategoryName, ProductCategoryKey, ProductCategoryAlternateKey, EnglishProductCategoryName)
SELECT Dim Product.ProductKey, Dim Product.ProductAlternateKey, Dim Product.ProductSubcategoryKey, Dim Product.WeightUnitMeasureCode, Dim Product.SizeUnitMeasureCode, Dim Product.EnglishProductName, Dim Product.StandardCost, Dim Product.FinishedGoodsFlag, Dim Product.Color, Dim Product.SafetyStockLevel, Dim Product.ReorderPoint, Dim Product.ListPrice, Dim Product.Size, Dim Product.SizeRange, Dim Product.Weight, Dim Product.DaysToManufacture, Dim Product.ProductLine, Dim Product.DealerPrice, Dim Product.Class, Dim Product.Style, Dim Product.ModelName, Dim Product.EnglishDescription, Dim Product.StartDate, Dim Product.EndDate, Dim Product.Status, Dim Product.ProductSubCategoryName, Dim Product.ProductCategoryName, Dim Product Subcategory.ProductSubcategoryAlternateKey, Dim Product Subcategory.EnglishProductSubcategoryName, Dim Product Subcategory.ProductCategoryKey, Dim Product Category.ProductCategoryAlternateKey, Dim Product Category.EnglishProductCategoryName
FROM Dim Product JOIN Dim Product Subcategory ON Dim Product.ProductSubcategoryKey = Dim Product Subcategory.ProductSubcategoryKey JOIN Dim Product Category ON Dim Product.ProductCategoryKey = Dim Product Category.ProductCategoryKey;

INSERT INTO Dim Employee (EmployeeKey, ParentEmployeeKey, EmployeeNationalIDAlternateKey, ParentEmployeeNationalIDAlternateKey, SalesTerritoryKey, FirstName, LastName, MiddleName, NameStyle, Title, HireDate, BirthDate, LoginID, EmailAddress, Phone, MaritalStatus, EmergencyContactName, EmergencyContactPhone, SalariedFlag, Gender, PayFrequency, BaseRate, VacationHours, SickLeaveHours, CurrentFlag, SalesPersonFlag, DepartmentName, StartDate, EndDate, Status, FullName, Path, Level1, Level2, Level3, Level4, Level5)
SELECT Dim Employee.EmployeeKey, Dim Employee.ParentEmployeeKey, Dim Employee.EmployeeNationalIDAlternateKey, Dim Employee.ParentEmployeeNationalIDAlternateKey, Dim Employee.SalesTerritoryKey, Dim Employee.FirstName, Dim Employee.LastName, Dim Employee.MiddleName, Dim Employee.NameStyle, Dim Employee.Title, Dim Employee.HireDate, Dim Employee.BirthDate, Dim Employee.LoginID, Dim Employee.EmailAddress, Dim Employee.Phone, Dim Employee.MaritalStatus, Dim Employee.EmergencyContactName, Dim Employee.EmergencyContactPhone, Dim Employee.SalariedFlag, Dim Employee.Gender, Dim Employee.PayFrequency, Dim Employee.BaseRate, Dim Employee.VacationHours, Dim Employee.SickLeaveHours, Dim Employee.CurrentFlag, Dim Employee.SalesPersonFlag, Dim Employee.DepartmentName, Dim Employee.StartDate, Dim Employee.EndDate, Dim Employee.Status, Dim Employee.FullName, Dim Employee.Path, Dim Employee.Level1, Dim Employee.Level2, Dim Employee.Level3, Dim Employee.Level4, Dim Employee.Level5
FROM Dim Employee;

INSERT INTO Fact Internet Sales (CustomerKey, ProductKey, DueDateKey, ShipDateKey, OrderDateKey, PromotionKey, CurrencyKey, SalesTerritoryKey, SalesOrderNumber, SalesOrderLineNumber, RevisionNumber, OrderQuantity, UnitPrice, ExtendedAmount, UnitPriceDiscountPct, DiscountAmount, ProductStandardCost, TotalProductCost, SalesAmount, TaxAmt, Freight, CarrierTrackingNumber, CustomerPONumber, OrderDate, DueDate, ShipDate, Margin)
SELECT CustomerKey, ProductKey, DueDateKey, ShipDateKey, OrderDateKey, PromotionKey, CurrencyKey, SalesTerritoryKey, SalesOrderNumber, SalesOrderLineNumber, RevisionNumber, OrderQuantity, UnitPrice, ExtendedAmount, UnitPriceDiscountPct, DiscountAmount, ProductStandardCost, TotalProductCost, SalesAmount, TaxAmt, Freight, CarrierTrackingNumber, CustomerPONumber, OrderDate, DueDate, ShipDate, Margin
FROM Fact Internet Sales;

INSERT INTO Fact Reseller Sales (EmployeeKey, ProductKey, OrderDateKey, DueDateKey, ShipDateKey, ResellerKey, PromotionKey, CurrencyKey, SalesTerritoryKey, SalesOrderNumber, SalesOrderLineNumber, RevisionNumber, OrderQuantity, UnitPrice, ExtendedAmount, UnitPriceDiscountPct, DiscountAmount, ProductStandardCost, TotalProductCost, SalesAmount, TaxAmt, Freight, CarrierTrackingNumber, CustomerPONumber, OrderDate, DueDate, ShipDate)
SELECT EmployeeKey, ProductKey, OrderDateKey, DueDateKey, ShipDateKey, ResellerKey, PromotionKey, CurrencyKey, SalesTerritoryKey, SalesOrderNumber, SalesOrderLineNumber, RevisionNumber, OrderQuantity, UnitPrice, ExtendedAmount, UnitPriceDiscountPct, DiscountAmount, ProductStandardCost, TotalProductCost, SalesAmount, TaxAmt, Freight, CarrierTrackingNumber, CustomerPONumber, OrderDate, DueDate, ShipDate
FROM Fact Reseller Sales;

-- NOTES (read these)
-- Fact Internet Sales: 18 calculated/sourceless measures require manual SQL: InternetDistinctCountSalesOrder, InternetOrderLinesCount, InternetTotalUnits, InternetTotalDiscountAmount, InternetTotalProductCost
-- Fact Reseller Sales: 1 calculated/sourceless measures require manual SQL: ResellerTotalSales
